name: geo

channels:
  - conda-forge

dependencies:
  - python=3.9
  - contextily
  - cykhash=2.0.0
  - folium
  - geopandas
  - geopy
  - jupyterlab=3.0.6
  - jupyterlab-git
  - mapclassify
  - matplotlib
  - movingpandas
  - networkx
  - osmnx
  - pandas
  - pyrosm
  - r5py
  - pip
  - pip:
      - keplergl
