name: geo

channels:
  - conda-forge

dependencies:
  - python=3.10
  - cykhash=2.0.0
  - fiona=1.8.22
  - folium
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geopy
  - git
  - jupyterlab=3.0.6
  - jupyterlab-git
  - libgdal=3.6.2
  - mapclassify
  - matplotlib
  - networkx
  - openjdk=11.0.1
  - osmnx
  - pandas
  - pyrosm
  - pysal
  - python-igraph
  - r5py
  - shapely=1.8.5
  - tqdm
