name: base

channels:
  - conda-forge

dependencies:
  - python=3.10
  - access
  - contextily
  - cykhash=2.0.0
  - dash
  - elevation
  - fiona=1.8.22
  - folium
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geoplot
  - geopy
  - git
  - hvplot
  - jupyterlab=3.0.6
  - jupyterlab-git
  - libgdal=3.6.2
  - mamba
  - mapclassify
  - matplotlib
  - momepy
  - movingpandas
  - networkx
  - openjdk=11.0.1
  - osmnx
  - pandana
  - pandas
  - plotly_express
  - pyrosm
  - pysal
  - python-igraph
  - r5py
  - rasterio
  - rioxarray
  - scikit-learn
  - scikit-mobility
  - scipy
  - segregation
  - shapely=1.8.5
  - spaghetti
  - splot
  - spreg
  - tqdm
  - urbanaccess
  - xarray